"""empty message

Revision ID: f85cf907007d
Revises: 55f2a2db6ef5
Create Date: 2018-01-23 14:30:52.476416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85cf907007d'
down_revision = '55f2a2db6ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'priority')
    # ### end Alembic commands ###
